### ISSUE TITLE
Feedback 1° Sprint

### ISSUE THREAD

**Issue by nerdale** [VioletaLibertad/scl-2018-05-bc-core-am#1]
Violeta,

Felicitaciones por el orden de tu código, buena indentación y comentarios en el archivo **index.html**, en el archivo **style.css** estás indentando con 4 espacios y deberían ser 2.

Te sugiero comenzar a trabajar la lógica para cumplir con el objetivo del deadline

**Comment by VioletaLibertad** [comment]
Gracias por el Feedback! Estoy trabajando en la logica ahora :)
